name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    # 00:00 every day(https://crontab.guru/#0_0_*_*_*)
    - cron: "0 0 * * *"
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run & Save
        run: |
          cargo run > docs/"$(date --date=yesterday +'%Y%m%d').md"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
