name: Trigger Tweet on a CRON Schedule

on:
  schedule:
    # 00:00 every day(https://crontab.guru/#0_0_*_*_*)
    - cron: "0 0 * * *"
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Tweet
        run: |
          cargo run
        env:
          TOGGL_EMAIL: ${{ secrets.TOGGL_EMAIL }}
          TOGGL_PASSWORD: ${{ secrets.TOGGL_PASSWORD }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}